### ISSUE TITLE
Word change

### ISSUE THREAD

**Issue by Nikki-Luoma** [nadeld/nadeld.github.io#6]
In the first paragraph you have, " value what their learning". I would suggest changing this to "value their learning" or "value what they're learning".

**Comment by Nikki-Luoma** [comment]
In the first paragraph you have, "also affect their", I would change this to "also affects their".

**Comment by Nikki-Luoma** [comment]
In the first paragraph you use the word "ultra-important" I feel that it should just be "important", but this is up to you.

**Comment by Nikki-Luoma** [comment]
In the first paragraph you have, "United States they have are infamous", I would change this to "United State are infamous".

**Comment by nadeld** [comment]
Thanks! I revised everything.

**Comment by Nikki-Luoma** [comment]
In the first paragraph, you have, "Boarding schools have started to implement hands on" it should be hands-on.

**Comment by Nikki-Luoma** [comment]
You have, "Especially since there are many students that have demanding schedules both academically and extracurically" but I think you should change extracurically.

**Comment by Nikki-Luoma** [comment]
"In addition, the presence of kids with psychological problems has increrased at an incredible 13 percent from 2013 to 2015" it should be "increased".

**Comment by Nikki-Luoma** [comment]
Sometimes in your paper, you have "NyTimes" and others you have "NYTime" I would standardize this.

**Comment by Nikki-Luoma** [comment]
In the final paragraph, you have, "We need to take away grades from universities. One school that has practices this is University of California, Redlands and Sierra Lawrence College."  In this sentences the verbs do not match, you can either say, "that practices" or "has practiced". (If the school is still doing this I would pick the present tense).

**Comment by Nikki-Luoma** [comment]
In the last paragraph, you have, ". Technology has made it possible for different ways of learning curriculum**,** and games would keep kids engaged in the classroom", but you do not need the comma.

**Comment by nadeld** [comment]
Thanks for your feedback! Much appreciated!
