### ISSUE TITLE
Final Paper

### ISSUE THREAD

**Issue by Nikki-Luoma** [nadeld/nadeld.github.io#8]
Your subtitle is, "A growing company in Amazon has hurt local business all throughout the United States," I do not understand why you are using the word "in" it does not seem fitting.

**Comment by Nikki-Luoma** [comment]
The third paragraph stops midsentence.

**Comment by Nikki-Luoma** [comment]
In the fourth paragraph, you have, " Also since Amazon is likely..." it should be, "Also,"

**Comment by Nikki-Luoma** [comment]
You're off to a good start, one of my suggestions is to introduce exercise, Amazon's partnerships and YouTue in your introduction paragraph. Right now your introduction is focused on Twitch despite your article having more to it.

**Comment by nadeld** [comment]
Thank you!

**Comment by Nikki-Luoma** [comment]
In the first paragraph, you have, "this saved me $20 that I did not have to pay because I am an Amazon Prime member", but I think this is too repetitive. I would suggest changing it to, "this saved me $20 since I am an Amazon Prime member."

**Comment by nadeld** [comment]
Cool, Just fixed that!

**Comment by Nikki-Luoma** [comment]
In the second paragraph you have, "While Amazon is a go to source for everything shopping related there is one major drawback. That drawback...", this feels repetitive, I would just add what the drawback is to that sentence.

**Comment by Nikki-Luoma** [comment]
In the second paragraph you use the word monopoly, yet you talk about competition. I would say Amazon has a large part of the market, ect. but the word monopoly does not seem fitting.

**Comment by Nikki-Luoma** [comment]
In the second paragraph, you have "also" but it needs a comma after it, "also,".

**Comment by Nikki-Luoma** [comment]
Isn't the "Twitch streamer" the person viewing and not the content creator?

**Comment by Nikki-Luoma** [comment]
The first part of the second paragraph talks about Twitch and the second half talks about exercise, consider making these two different paragraphs since they do not have the same topics.

**Comment by Nikki-Luoma** [comment]
In the third paragraph I do not understand the comparison between YouTube and their viewers being compared to local businesses and Amazon.

**Comment by Nikki-Luoma** [comment]
Since your article is about how Amazon is hurting businesses and could create a monopoly, I do not see why YouTube is being discussed since Amazon is not hurting them.

**Comment by Nikki-Luoma** [comment]
You have "This is discouraging because as Amazon pushes toward automation, consumers will miss out on going to a store and getting that interaction between employee and consumer" but it should be, "This is discouraging because as Amazon pushes toward automation, and consumers will miss out on going to a store and getting that interaction between employee and consumer. "

**Comment by Nikki-Luoma** [comment]
After lastly you need a comma.

**Comment by Nikki-Luoma** [comment]
"Amazon has now signs of slowing down" it should be,  "Amazon has no signs of slowing down"

**Comment by Nikki-Luoma** [comment]
In your last paragraph you talk about how Amazon can you the sale tax they collect to make more warehouses, but sale tax goes to the Government. You should explain this a bit more.

**Comment by nadeld** [comment]
Thanks Nikki! I took all of your responses into consideration.
